/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.solace.demo.taxi;

import java.io.FileNotFoundException;
import java.io.IOException;

import org.junit.Test;

public class RideTests {
    @Test
    public void testNewRides() throws FileNotFoundException, IOException {
        RouteLoader.INSTANCE.load("coords_01.txt");
        System.out.println(Ride.newRide());
        System.out.println(Ride.newRide());
        System.out.println(Ride.newRide());
        System.out.println(Ride.newRide());
        System.out.println(Ride.newRide());
        System.out.println(Ride.newRide());
        System.out.println(Ride.newRide());
        System.out.println(Ride.newRide());
    
        Ride ride = Ride.newRide();
        
        ride.tick();
        ride.tick();
        ride.tick();
        ride.tick();
        ride.tick();
        ride.tick();
        ride.tick();
        ride.tick();
        ride.tick();
        ride.tick();
        while (ride.getStatus() == Ride.Status.EN_ROUTE) {
            ride.tick();
        }
    }
    
    
}
