/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.solace.demo.taxi;

import org.junit.Test;

public class DriverTests {
    @Test
    public void testNewDrivers() {
        System.out.println(Driver.newInstance());
        System.out.println(Driver.newInstance());
        System.out.println(Driver.newInstance());
        System.out.println(Driver.newInstance());
        System.out.println(Driver.newInstance());
        System.out.println(Driver.newInstance());
        System.out.println(Driver.newInstance());
        System.out.println(Driver.newInstance());
        System.out.println(Driver.newInstance());
        System.out.println(Driver.newInstance());
        System.out.println(Driver.newInstance());
        System.out.println(Driver.newInstance());
    }
    
    
}
